BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `serie` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`rep`	REAL NOT NULL,
	`charge`	REAL NOT NULL,
	`ordre`	INTEGER NOT NULL,
	`idSeance`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `seance` (
	`idSeance`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ordre`	INTEGER NOT NULL,
	`intensite`	INTEGER,
	`commentaire`	TEXT,
	`idExercice`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `programme` (
	`idProgramme`	INTEGER NOT NULL UNIQUE,
	`nom`	TEXT NOT NULL,
	`ordre`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `exercice` (
	`idExercice`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nom`	TEXT NOT NULL,
	`ordre`	INTEGER NOT NULL,
	`idEntrainement`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `entrainement` (
	`idEntrainement`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nom`	TEXT NOT NULL,
	`ordre`	INTEGER NOT NULL,
	`idProgramme`	TEXT NOT NULL
);
COMMIT;
